version: "3.1"
services:
  cassandra:
    image: cassandra:4
    networks:
      default:
        aliases:
          - cassandra_db
    ports:
      - "9042:9042"

  informer-service:
    build: .
    image: informer
    depends_on:
      - cassandra
    env_file:
#      - ./.env
      - ./config/.dev.env
    volumes:
      - .:/app
    networks:
      default:
        aliases:
          - informer_service
    ports:
      - "8080:8080"