version: "3.8"

services:
  postgres:
    image: postgres:14.5
    networks:
      default:
        aliases:
          - postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  profiler-service:
    build:
      context: ./profiler
      dockerfile: Dockerfile
    image: profiler
    depends_on:
      - postgres
    environment:
      - PORT=8080
      - DB_CONN_STRING=postgresql://admin:admin@postgres_db
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - JWT_KMS_KEY_ID=${JWT_KMS_KEY_ID}
    volumes:
      - .:/app
    networks:
      default:
        aliases:
          - profiler_service
    ports:
      - "8080:8080"

  pet-rock:
    build:
      context: ./pet-rock
      dockerfile: Dockerfile
    ports:
      - "9000:8080"
    environment:
      AWS_REGION: ap-southeast-1
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      PROFILER_ENDPOINT: http://profiler_service:8080