info:
  contact: {}
paths:
  /campaign:
    get:
      consumes:
      - application/json
      description: Get all campaigns
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Get all campaigns
      tags:
      - example
  /health:
    get:
      consumes:
      - application/json
      description: health check
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: healthcheck example
      tags:
      - example
swagger: "2.0"
