version: "3.8"

services:
  ingestor:
    build: .
    ports:
      - 9000:8080
    environment:
      AWS_REGION: ap-southeast-1
      AWS_ACCESS_KEY_ID: AKIAUAWJVJ7I7A4V3QI6
      AWS_SECRET_ACCESS_KEY: 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