apiVersion: apps/v1
kind: Deployment
metadata:
  name: campaignex-deployment
  labels:
    app: campaignex
spec:
  replicas: 3
  selector:
    matchLabels:
      app: campaignex
  template:
    metadata:
      labels:
        app: campaignex
    spec:
      containers:
        - name: campaignex-cnt
          image: 276374573009.dkr.ecr.ap-southeast-1.amazonaws.com/campaignex:{{.Values.deployment.imageTag}}
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: ETCD_ENDPOINTS
              value: etcd.angelowl-etcd:2379
            - name: ETCD_USERNAME
              valueFrom:
                secretKeyRef:
                  name: etcd
                  key: username
            - name: ETCD_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: etcd
                  key: password
            - name: DB_CONN_STRING
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: connection
