deployment:
  imageTag: d3dae42c2fbe3dbdadf6417ed3108aba9eae364b

app:
  name: campaignex
  port: 8080
  replicas: 2
  env:
    - name: PORT
      value: "8080"
    - name: ETCD_ENDPOINTS
      value: etcd.angelowl-etcd:2379
    - name: ETCD_USERNAME
      valueFrom:
        secretKeyRef:
          name: etcd
          key: username
    - name: ETCD_PASSWORD
      valueFrom:
        secretKeyRef:
          name: etcd
          key: password
    - name: DB_CONN_STRING
      valueFrom:
        secretKeyRef:
          name: campaignex
          key: database