version: "3.8"

services:
  emailer:
    build: .
    ports:
      - "9000:8080"
    environment:
      AWS_REGION: ap-southeast-1
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      CASSANDRA_CONN_STRING: ${CASSANDRA_CONN_STRING}
      CASSANDRA_KEYSPACE: ${CASSANDRA_KEYSPACE}
      CASSANDRA_TABLE: ${CASSANDRA_TABLE}
      CASSANDRA_PORT: ${CASSANDRA_PORT}
      CASSANDRA_USERNAME: ${CASSANDRA_USERNAME}
      CASSANDRA_PASSWORD: ${CASSANDRA_PASSWORD}
      POSTGRES_CONN_STRING: ${POSTGRES_CONN_STRING}