version: "3.8"

services:
  emailer:
    build: .
    ports:
      - "9000:8080"
    environment:
      AWS_REGION: ap-southeast-1
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      INFORMER_ENDPOINT: ${INFORMER_ENDPOINT}
      POSTGRES_CONN_STRING: ${POSTGRES_CONN_STRING}