version: "3.1"
services:
  cassandra:
    image: cassandra:4
    networks:
      default:
        aliases:
          - cassandra_db
    ports:
      - "9042:9042"

  rewarder-service:
    build: .
    image: rewarder
    depends_on:
      - cassandra
    environment:
      - DB_CONN_STRING=cassandra_db
      - DB_KEYSPACE=transactions
      - DB_TABLE=rewards
      - BROKER_HOST=angelowlmsk.aznt6t.c3.kafka.ap-southeast-1.amazonaws.com:9092
      - TOPIC=transaction7
    volumes:
      - .:/app
    networks:
      default:
        aliases:
          - rewarder_service
    ports:
      - "8080:8080"
  
  # zookeeper:
  #   image: confluentinc/cp-zookeeper:7.3.0
  #   container_name: zookeeper
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181
  #     ZOOKEEPER_TICK_TIME: 2000

  # broker:
  #   image: confluentinc/cp-kafka:7.3.0
  #   container_name: broker
  #   networks:
  #     default:
  #       aliases:
  #         - broker
  #   ports:
  #     - "9092:9092"
  #   depends_on:
  #     - zookeeper
  #   environment:
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_INTERNAL://broker:29092
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #     KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
  #     KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  # kafka-ui:
  #   image: provectuslabs/kafka-ui
  #   container_name: kafka-ui
  #   ports:
  #     - "3000:3000"
  #   # restart: always
  #   environment:
  #     - KAFKA_CLUSTERS_0_NAME=localhost
  #     - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=localhost:9092