version: "3.1"

volumes:
  etcd_data:
    driver: local

services:
  cassandra:
    image: cassandra:4
    networks:
      default:
        aliases:
          - cassandra_db
    ports:
      - "9042:9042"

  rewarder-service:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    image: rewarder
    depends_on:
      - cassandra
    environment:
      - DB_CONN_STRING=cassandra_db
      - DB_KEYSPACE=transactions
      - DB_TABLE=rewards
      - BROKER_HOST=angelowlmsk.aznt6t.c3.kafka.ap-southeast-1.amazonaws.com:9092
      - TOPIC=transaction7
      - ETCD_ENDPOINTS=http://etcd:2379
    volumes:
      - .:/app
    networks:
      default:
        aliases:
          - rewarder_service

  etcd:
    image: 'bitnami/etcd:latest'
    networks:
      default:
        aliases:
          - etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - "2379:2379"
  