apiVersion: v1
kind: Service
metadata:
  name: {{.Values.app.name}}-svc
spec:
  type: NodePort
  selector:
    app: {{.Values.app.name}}
  ports:
  - name: {{.Values.app.name}}-svc
    protocol: TCP
    port: 80
    targetPort: 8080