kind: ServiceAccount
apiVersion: v1
metadata:
  name: angelowl-{{ .Values.app.name }}-sa
  annotations:
    {{ if .Values.app.roleArn }}}
        eks.amazonaws.com/role-arn: {{ .Values.app.roleArn | quote }}
    {{ end }}