definitions:
  models.Campaign:
    properties:
      end_date:
        description: should be later than Start
        type: string
      id:
        type: string
      mcc:
        maximum: 9999
        minimum: 1
        type: integer
      merchant:
        minLength: 1
        type: string
      min_spend:
        minimum: 0
        type: number
      name:
        minLength: 1
        type: string
      reward_amount:
        type: integer
      reward_program:
        minLength: 1
        type: string
      start_date:
        description: 'TODO: Add back the gte to add validation after time now'
        type: string
    required:
    - end_date
    - mcc
    - merchant
    - name
    - reward_amount
    - reward_program
    - start_date
    type: object
  models.Exclusion:
    properties:
      id:
        type: string
      mcc:
        maximum: 9999
        minimum: 1
        type: integer
      valid_from:
        description: 'TODO: Add back the gte to add validation after time now'
        type: string
    required:
    - mcc
    - valid_from
    type: object
info:
  contact: {}
paths:
  /campaign:
    get:
      description: Get all campaigns
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Campaign'
            type: array
      summary: Get all campaigns
      tags:
      - campaign
    post:
      consumes:
      - application/json
      description: Create a campaign
      parameters:
      - description: New Campaign
        in: body
        name: campaign
        required: true
        schema:
          $ref: '#/definitions/models.Campaign'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Campaign'
      summary: Create a campaign
      tags:
      - campaign
  /campaign/{campaign_id}:
    delete:
      description: Delete a campaign
      parameters:
      - description: Campaign ID
        in: path
        name: campaign_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: Delete a campaign
      tags:
      - campaign
    get:
      description: Get a single campaign by its UUID
      parameters:
      - description: Campaign ID
        in: path
        name: campaign_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Campaign'
      summary: Get a campaign
      tags:
      - campaign
    put:
      consumes:
      - application/json
      description: Update a campaign
      parameters:
      - description: New Campaign
        in: body
        name: campaign
        required: true
        schema:
          $ref: '#/definitions/models.Campaign'
      - description: Campaign ID
        in: path
        name: campaign_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Campaign'
      summary: Update a campaign
      tags:
      - campaign
  /exclusion:
    get:
      description: Get all exclusions
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Exclusion'
            type: array
      summary: Get all exclusions
      tags:
      - exclusion
    post:
      consumes:
      - application/json
      description: Create an exclusion
      parameters:
      - description: New Exclusion
        in: body
        name: exclusion
        required: true
        schema:
          $ref: '#/definitions/models.Exclusion'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Exclusion'
      summary: Create an exclusion
      tags:
      - exclusion
  /exclusion/{exclusion_id}:
    delete:
      description: Delete an exclusion
      parameters:
      - description: Exclusion ID
        in: path
        name: exclusion_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: Delete an exclusion
      tags:
      - exclusion
    get:
      description: Get a single exclusion by its UUID
      parameters:
      - description: Exclusion ID
        in: path
        name: exclusion_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Exclusion'
      summary: Get an exclusion
      tags:
      - exclusion
    put:
      consumes:
      - application/json
      description: Update an exclusion
      parameters:
      - description: New Exclusion
        in: body
        name: exclusion
        required: true
        schema:
          $ref: '#/definitions/models.Exclusion'
      - description: Exclusion ID
        in: path
        name: exclusion_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Exclusion'
      summary: Update an exclusion
      tags:
      - exclusion
  /health:
    get:
      description: health check
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: health
swagger: "2.0"
