name: Continuous Integration (Authorizer)

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ master ]

permissions:
  id-token: write
  contents: read 

jobs:
  ci:
    name: Continuous Integration
    uses: ./.github/workflows/workflow_lambda.yml
    with:
      dockerfile: 'Dockerfile'
      workdir: 'authorizer'