name: Continuous Integration (Authorizer)

on:
  push:
    branches: [ master ]
    paths:
      - "authorizer/**"
      - .github/workflows/ci_authorizer.yml
      - .github/workflows/workflow_lambda.yml

permissions:
  id-token: write
  contents: read 

jobs:
  lint:
    name: Golang Linting
    uses: ./.github/workflows/golangci-lint.yml
    with:
      workdir: 'authorizer'
  sast:
    needs: lint
    name: Golang SAST
    uses: ./.github/workflows/sast_golang.yml
    with:
      workdir: 'authorizer'
  ci:
    needs: [lint, sast]
    name: Continuous Integration
    uses: ./.github/workflows/workflow_lambda.yml
    with:
      dockerfile: 'Dockerfile'
      workdir: 'authorizer'
      repository: 'authorizer'
      lambda_name: 'angel-owl-authorizer'
      execution_role_arn: 'arn:aws:iam::276374573009:role/service-role/angel-owl-authorizer-role-oq6y0qqe'