name: Continuous Integration (Authorizer)

on:
  push:
    branches: [ '**' ]
    paths:
      - "authorizer/**"
      - .github/workflows/ci_authorizer.yml
      - .github/workflows/workflow_lambda.yml
  pull_request:
    branches: [ master ]
    paths:
      - "authorizer/**"
      - .github/workflows/ci_authorizer.yml
      - .github/workflows/workflow_lambda.yml

permissions:
  id-token: write
  contents: read 

jobs:
  lint:
    name: Golang Linting
    uses: ./.github/workflows/golangci-lint.yml
    with:
      workdir: 'authorizer'
  gosec:
    needs: lint
    name: gosec SAST
    uses: ./.github/workflows/gosec.yml
    with:
      workdir: 'authorizer'
  semgrep:
    needs: lint
    name: semgrep SAST
    uses: ./.github/workflows/semgrep.yml
    with:
      workdir: 'authorizer'
  ci:
    needs: [lint, gosec]
    name: Continuous Integration
    uses: ./.github/workflows/workflow_lambda.yml
    with:
      dockerfile: 'Dockerfile'
      workdir: 'authorizer'
      repository: 'authorizer'