name: Continuous Integration (Campaignex)

on:
  push:
    branches: [ '**' ]
    paths:
      - "campaignex/**"
      - .github/workflows/ci_campaignex.yml
      - .github/workflows/workflow_container.yml
  pull_request:
    branches: [ master ]
    paths:
      - "campaignex/**"
      - .github/workflows/ci_campaignex.yml
      - .github/workflows/workflow_container.yml

permissions:
  id-token: write
  contents: read 

jobs:
  lint:
    name: Golang Linting
    uses: ./.github/workflows/golangci-lint.yml
    with:
      workdir: 'campaignex'
  sast:
    needs: lint
    name: Golang SAST
    uses: ./.github/workflows/sast_golang.yml
    with:
      workdir: 'campaignex'
  ci:
    needs: [lint, sast]
    name: Continuous Integration
    uses: ./.github/workflows/workflow_container.yml
    with:
      dockerfile: 'Dockerfile.prod'
      workdir: 'campaignex'
      repository: 'campaignex'