name: Continuous Integration (Ingestor)

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    shell: bash
    working-directory: informer

permissions:
  id-token: write
  contents: read 

jobs:
  ci-informer:
    name: CI for Informer
    uses: ./.github/workflows/workflow_container.yml
    with:
      dockerfile: 'Dockerfile.prod'