name: Continuous Integration (Ingestor)

on:
  push:
    branches: [ '**' ]
    paths:
      - "ingestor/**"
      - .github/workflows/ci_ingestor.yml
      - .github/workflows/workflow_lambda.yml
  pull_request:
    branches: [ master ]
    paths:
      - "ingestor/**"
      - .github/workflows/ci_ingestor.yml
      - .github/workflows/workflow_lambda.yml

permissions:
  id-token: write
  contents: read 

jobs:
  lint:
    name: Golang Linting
    uses: ./.github/workflows/golangci-lint.yml
    with:
      workdir: 'ingestor'
  sast:
    needs: lint
    name: Golang SAST
    uses: ./.github/workflows/sast_golang.yml
    with:
      workdir: 'ingestor'
  ci:
    needs: [lint, sast]
    name: Continuous Integration
    uses: ./.github/workflows/workflow_lambda.yml
    with:
      dockerfile: 'Dockerfile'
      workdir: 'ingestor'
      repository: 'ingestor'
      lambda_name: 'angel-owl-publish-to-msk'
      execution_role_arn: 'arn:aws:iam::276374573009:role/angel-owl-publish-to-msk'
