name: Continuous Integration (Profiler)

on:
  push:
    branches: [ '**' ]
    paths:
      - "profiler/**"
      - .github/workflows/ci_profiler.yml
      - .github/workflows/workflow_container.yml
  pull_request:
    branches: [ master ]
    paths:
      - "profiler/**"
      - .github/workflows/ci_profiler.yml
      - .github/workflows/workflow_container.yml

permissions:
  id-token: write
  contents: read 

jobs:
  lint:
    name: Golang Linting
    uses: ./.github/workflows/golangci-lint.yml
    with:
      workdir: 'profiler'
  sast:
    name: Golang SAST
    uses: ./.github/workflows/gosec.yml
    with:
      workdir: 'profiler'
#  gosec:
#    needs: lint
#    name: gosec SAST
#    uses: ./.github/workflows/gosec.yml
#    with:
#      workdir: 'profiler'
#  semgrep:
#    needs: lint
#    name: semgrep SAST
#    uses: ./.github/workflows/semgrep.yml
#    with:
#      workdir: 'profiler'
  ci:
    needs: [lint, sast]
    name: Continuous Integration
    uses: ./.github/workflows/workflow_container.yml
    with:
      dockerfile: 'Dockerfile.prod'
      workdir: 'profiler'
      repository: 'profiler'