name: Continuous Integration (Profiler)

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    shell: bash
    working-directory: profiler

permissions:
  id-token: write
  contents: read 

jobs:
  ci-profiler:
    name: CI for Profiler
    uses: ./.github/workflows/workflow_container.yml
    with:
      dockerfile: 'Dockerfile.prod'