name: Continuous Integration (Passworder)

on:
  push:
    branches: [ '**' ]
    paths:
      - "passworder/**"
      - .github/workflows/ci_passworder.yml
      - .github/workflows/workflow_lambda.yml
  pull_request:
    branches: [ master ]
    paths:
      - "passworder/**"
      - .github/workflows/ci_passworder.yml
      - .github/workflows/workflow_lambda.yml

permissions:
  id-token: write
  contents: read

jobs:
  lint:
    name: Golang Linting
    uses: ./.github/workflows/golangci-lint.yml
    with:
      workdir: 'passworder'
  sast:
    needs: lint
    name: Golang SAST
    uses: ./.github/workflows/sast_golang.yml
    with:
      workdir: 'passworder'
  ci:
    needs: [lint, sast]
    name: Continuous Integration
    uses: ./.github/workflows/workflow_lambda.yml
    with:
      dockerfile: 'Dockerfile'
      workdir: 'passworder'
      repository: 'passworder'
      lambda_name: 'angel-owl-passworder'
      execution_role_arn: 'arn:aws:iam::276374573009:role/service-role/angel-owl-passworder-role-93i1ufh1'
