name: Continuous Integration (Rewarder)

on:
  push:
    branches: [ '**' ]
    paths:
      - "rewarder/**"
      - .github/workflows/ci_rewarder.yml
      - .github/workflows/workflow_container.yml
  pull_request:
    branches: [ master ]
    paths:
      - "rewarder/**"
      - .github/workflows/ci_rewarder.yml
      - .github/workflows/workflow_container.yml

permissions:
  id-token: write
  contents: read 

jobs:
  lint:
    name: Golang Linting
    uses: ./.github/workflows/golangci-lint.yml
    with:
      workdir: 'rewarder'
  ci:
    needs: lint
    name: Continuous Integration
    uses: ./.github/workflows/workflow_container.yml
    with:
      dockerfile: 'Dockerfile.prod'
      workdir: 'rewarder'
      repository: 'rewarder'