name: Continuous Integration (Rewarder)

on:
  push:
    branches: [ master ]
    paths:
      - ".chart/**"
      - "rewarder/**"
      - .github/workflows/ci_rewarder.yml
      - .github/workflows/workflow_container.yml

permissions:
  id-token: write
  contents: read 

jobs:
  lint:
    name: Golang Linting
    uses: ./.github/workflows/golangci-lint.yml
    with:
      workdir: 'rewarder'
  sast:
    needs: lint
    name: Golang SAST
    uses: ./.github/workflows/sast_golang.yml
    with:
      workdir: 'rewarder'
  test:
    needs: [lint, sast]
    name: Golang Test
    uses: ./.github/workflows/test_golang.yml
    with:
      workdir: 'rewarder'
  ci:
    needs: [lint, sast, test]
    name: Continuous Integration
    uses: ./.github/workflows/workflow_container.yml
    with:
      dockerfile: 'Dockerfile.prod'
      workdir: 'rewarder'
      repository: 'rewarder'