on:
  workflow_call:
    inputs:
      workdir:
        description: 'Working directory'
        required: true
        type: string

jobs:
  gosec:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: gosec
        uses: securego/gosec@master
        with:
          args: ./${{ inputs.workdir }}/...
