on:
  workflow_call:
    inputs:
      workdir:
        description: 'Working directory'
        required: true
        type: string

jobs:
  gosec:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.workdir }}
    env:
      GO111MODULE: on
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: gosec
        uses: securego/gosec@master
        with:
          args: ./...
