on:
  workflow_call:
    inputs:
      workdir:
        description: 'Working directory'
        required: true
        type: string

  semgrep:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: semgrep ci
        with:
          working-directory: ${{ inputs.workdir }}
        env:
          SEMGREP_RULES: p/default,p/golang