on:
  workflow_call:
    inputs:
      workdir:
        description: 'Working directory'
        required: true
        type: string

jobs:
  semgrep:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: semgrep ci --include=${{ inputs.workdir }} || true
        env:
          SEMGREP_RULES: p/default p/golang