name: Telegram Send (PR Open)

on:
  pull_request_target:
    branches: [ "master" ]
    types: [ "opened", "reopened" ]

permissions:
  contents: read

jobs:
  send-telegram:
    name: Telegram Send (PR Open)
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
          
      - name: Telegram Notify
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            [${{ github.actor }}](github.com/${{ github.actor }}) opened a Pull Request.
            
            Title:
            ${{ github.pull_request.title }}
            
            URL:
            ${{ github.pull_request.html_url }}
            
            
