on:
  workflow_call:
    inputs:
      dockerfile:
        description: 'Dockerfile'
        required: true
        type: string
      workdir:
        description: 'Working directory'
        required: true
        type: string
      repository:
        description: 'Repository'
        required: true
        type: string
      lambda_name:
        description: 'Lambda Function Name'
        required: true
        type: string

defaults:
  run:
    shell: bash

jobs:
  workflow-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::276374573009:role/gh-actions-oidc-role
          aws-region: ap-southeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push Docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY:  ${{ inputs.repository }}
          IMAGE_TAG: ${{ github.sha }}
          DOCKERFILE: ${{ inputs.dockerfile }}
          WORKDIR: ${{ inputs.workdir }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG $WORKDIR -f $WORKDIR/$DOCKERFILE
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: AWS Lambda Deploy
        if: github.ref == 'refs/heads/master'
        uses: appleboy/lambda-action@v0.1.5
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_DEFAULT_REGION }}
          function_name: ${{ inputs.lambda_name }}
          image_uri: ${{ steps.login-ecr.outputs.registry }}/${{ inputs.repository }}:${{ github.sha }}
          dry_run: true